apiVersion: v1
kind: Pod
metadata:
  name: kuard
  annotations:
    rockman.roll/general: "about myself"
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 8080
          path: /healthy
        failureThreshold: 3
        periodSeconds: 5
        initialDelaySeconds: 5
        timeoutSeconds: 2
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      resources:
        requests:
          cpu: "500m"
          memory: "125Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"