apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2

  # period of time when readiness probe is successful
  # after that can roll out next portion
  minReadySeconds: 30

  # if rollout not happened during this period - mark as failed and rollback
  progressDeadlineSeconds: 600

  strategy:
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 0 # usually used when maxUnavailable == 0
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.12
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx
